# Generated by Django 4.0.3 on 2022-04-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('aadhar_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aadhar_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('aadhar_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('acc_number', models.IntegerField(null=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PastJobExperience',
            fields=[
                ('aadhar_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, null=True)),
                ('job_role', models.CharField(max_length=50, null=True)),
                ('yowexp', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('aadhar_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('dob', models.CharField(max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('aadhar_number', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=100, null=True)),
                ('yop', models.IntegerField(null=True)),
                ('percentage', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
