# Generated by Django 4.0.3 on 2022-04-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_address_postal_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastjobexperience',
            old_name='yowexp',
            new_name='experience_in_years',
        ),
    ]
